branch-defaults:
  master:
    environment: Portal-env
environment-defaults:
  Portal-env:
    branch: master
    repository: origin
global:
  application_name: portal
  default_ec2_keyname: null
  default_platform: Node.js 18 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
